source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
    gem "github-pages"
    gem "jekyll-remote-theme"
    gem "jekyll-relative-links"
end

gem "jekyll-seo-tag"
gem "csv"
gem "base64"
gem "webrick"
